apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o0od
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o0od
    app.kubernetes.io/part-of: tkrw-pr712-0075-0021-app
  name: devfile-sample-o0od
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-o0od
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-o0od
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-o0od@sha256:ce65daf5cbc1e257b9d49d88f01a1e7ba65d3b4634b4e7e69f899d5abf6a5d29
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
